// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_DROPOUTWORLD_H
#define __BINDINGS_DROPOUTWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct dropoutworld_string_t {
  uint8_t*ptr;
  size_t len;
} dropoutworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} dropoutworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} dropoutworld_list_u8_t;

typedef struct exports_planner_dropoutworld_plan_data_t {
  dropoutworld_list_f32_t   input;
  dropoutworld_list_f32_t   output;
  dropoutworld_string_t   reply_to;
  dropoutworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_dropoutworld_plan_data_t;

// Exported Functions from `planner:dropoutworld/plan`
void exports_planner_dropoutworld_plan_dropout(dropoutworld_list_f32_t *a, exports_planner_dropoutworld_plan_data_t *result_container, exports_planner_dropoutworld_plan_data_t *ret);

// Helper Functions

void dropoutworld_list_f32_free(dropoutworld_list_f32_t *ptr);

void dropoutworld_list_u8_free(dropoutworld_list_u8_t *ptr);

void exports_planner_dropoutworld_plan_data_free(exports_planner_dropoutworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void dropoutworld_string_set(dropoutworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void dropoutworld_string_dup(dropoutworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void dropoutworld_string_dup_n(dropoutworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void dropoutworld_string_free(dropoutworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
