package planner:negativeworld;

interface plan {

    record imagedata {
        width: u32,
        height: u32,
        pixels: list<u8>,
        reply-to: string
    }
  
    invert: func(img: imagedata) -> imagedata;
}

world negativeworld {

    export plan;

}