// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_GEMMWORLD_H
#define __BINDINGS_GEMMWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct gemmworld_string_t {
  uint8_t*ptr;
  size_t len;
} gemmworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} gemmworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} gemmworld_list_u8_t;

typedef struct exports_planner_gemmworld_plan_data_t {
  gemmworld_list_f32_t   input;
  gemmworld_list_f32_t   output;
  gemmworld_string_t   reply_to;
  gemmworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_gemmworld_plan_data_t;

// Exported Functions from `planner:gemmworld/plan`
void exports_planner_gemmworld_plan_gemm(uint32_t in_features, uint32_t out_features, gemmworld_list_f32_t *weights, gemmworld_list_f32_t *bias, exports_planner_gemmworld_plan_data_t *result_container, exports_planner_gemmworld_plan_data_t *ret);

// Helper Functions

void gemmworld_list_f32_free(gemmworld_list_f32_t *ptr);

void gemmworld_list_u8_free(gemmworld_list_u8_t *ptr);

void exports_planner_gemmworld_plan_data_free(exports_planner_gemmworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void gemmworld_string_set(gemmworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void gemmworld_string_dup(gemmworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void gemmworld_string_dup_n(gemmworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void gemmworld_string_free(gemmworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
