// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_BNWORLD_H
#define __BINDINGS_BNWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct bnworld_string_t {
  uint8_t*ptr;
  size_t len;
} bnworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} bnworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} bnworld_list_u8_t;

typedef struct exports_planner_bnworld_plan_data_t {
  bnworld_list_f32_t   input;
  bnworld_list_f32_t   output;
  bnworld_string_t   reply_to;
  bnworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_bnworld_plan_data_t;

// Exported Functions from `planner:bnworld/plan`
void exports_planner_bnworld_plan_bn(uint32_t channels, uint32_t h_in, uint32_t w_in, float epsilon, bnworld_list_f32_t *scale, bnworld_list_f32_t *beta, bnworld_list_f32_t *mean, bnworld_list_f32_t *var, exports_planner_bnworld_plan_data_t *img, exports_planner_bnworld_plan_data_t *ret);

// Helper Functions

void bnworld_list_f32_free(bnworld_list_f32_t *ptr);

void bnworld_list_u8_free(bnworld_list_u8_t *ptr);

void exports_planner_bnworld_plan_data_free(exports_planner_bnworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void bnworld_string_set(bnworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void bnworld_string_dup(bnworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void bnworld_string_dup_n(bnworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void bnworld_string_free(bnworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
