// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_GAPWORLD_H
#define __BINDINGS_GAPWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct gapworld_string_t {
  uint8_t*ptr;
  size_t len;
} gapworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} gapworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} gapworld_list_u8_t;

typedef struct exports_planner_gapworld_plan_data_t {
  gapworld_list_f32_t   input;
  gapworld_list_f32_t   output;
  gapworld_string_t   reply_to;
  gapworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_gapworld_plan_data_t;

// Exported Functions from `planner:gapworld/plan`
void exports_planner_gapworld_plan_gap(gapworld_list_f32_t *a, exports_planner_gapworld_plan_data_t *result_container, exports_planner_gapworld_plan_data_t *ret);

// Helper Functions

void gapworld_list_f32_free(gapworld_list_f32_t *ptr);

void gapworld_list_u8_free(gapworld_list_u8_t *ptr);

void exports_planner_gapworld_plan_data_free(exports_planner_gapworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void gapworld_string_set(gapworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void gapworld_string_dup(gapworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void gapworld_string_dup_n(gapworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void gapworld_string_free(gapworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
