package planner:sobelworld;

interface plan {

    record imagedata {
        width: u32,
        height: u32,
        pixels: list<u8>,
        reply-to: string,
        kernels: list<u8>,
        current-kernel: u32
    }

    sobel: func(img: imagedata) -> imagedata;
}

world sobelworld {

    export plan;

}