// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_ADDWORLD_H
#define __BINDINGS_ADDWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct addworld_string_t {
  uint8_t*ptr;
  size_t len;
} addworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} addworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} addworld_list_u8_t;

typedef struct exports_planner_addworld_plan_data_t {
  addworld_list_f32_t   input;
  addworld_list_f32_t   output;
  addworld_string_t   reply_to;
  addworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_addworld_plan_data_t;

// Exported Functions from `planner:addworld/plan`
void exports_planner_addworld_plan_add(addworld_list_f32_t *a, addworld_list_f32_t *b, exports_planner_addworld_plan_data_t *result_container, exports_planner_addworld_plan_data_t *ret);

// Helper Functions

void addworld_list_f32_free(addworld_list_f32_t *ptr);

void addworld_list_u8_free(addworld_list_u8_t *ptr);

void exports_planner_addworld_plan_data_free(exports_planner_addworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void addworld_string_set(addworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void addworld_string_dup(addworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void addworld_string_dup_n(addworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void addworld_string_free(addworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
