// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_CONVWORLD_H
#define __BINDINGS_CONVWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct convworld_string_t {
  uint8_t*ptr;
  size_t len;
} convworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} convworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} convworld_list_u8_t;

typedef struct exports_planner_convworld_plan_data_t {
  convworld_list_f32_t   input;
  convworld_list_f32_t   output;
  convworld_string_t   reply_to;
  convworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_convworld_plan_data_t;

// Exported Functions from `planner:convworld/plan`
void exports_planner_convworld_plan_conv(uint32_t c_out, uint32_t c_in, uint32_t h_in, uint32_t w_in, uint32_t kh, uint32_t kw, uint32_t stride, uint32_t padding, convworld_list_f32_t *weights, exports_planner_convworld_plan_data_t *img, exports_planner_convworld_plan_data_t *ret);

// Helper Functions

void convworld_list_f32_free(convworld_list_f32_t *ptr);

void convworld_list_u8_free(convworld_list_u8_t *ptr);

void exports_planner_convworld_plan_data_free(exports_planner_convworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void convworld_string_set(convworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void convworld_string_dup(convworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void convworld_string_dup_n(convworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void convworld_string_free(convworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
