package example:server;

world runner {
    import planner:addworld/plan;
    import planner:bnworld/plan;
    import planner:convworld/plan;
    import planner:dropoutworld/plan;
    import planner:flattenworld/plan;
    import planner:gapworld/plan;
    import planner:gemmworld/plan;
    import planner:maxpoolworld/plan;
    import planner:reluworld/plan;
    export wasi:cli/run@0.2.7;
}