// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_MAXPOOLWORLD_H
#define __BINDINGS_MAXPOOLWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct maxpoolworld_string_t {
  uint8_t*ptr;
  size_t len;
} maxpoolworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} maxpoolworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} maxpoolworld_list_u8_t;

typedef struct exports_planner_maxpoolworld_plan_data_t {
  maxpoolworld_list_f32_t   input;
  maxpoolworld_list_f32_t   output;
  maxpoolworld_string_t   reply_to;
  maxpoolworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_maxpoolworld_plan_data_t;

// Exported Functions from `planner:maxpoolworld/plan`
void exports_planner_maxpoolworld_plan_maxpool(uint32_t channels, uint32_t h_in, uint32_t w_in, uint32_t kh, uint32_t kw, uint32_t stride, uint32_t padding, exports_planner_maxpoolworld_plan_data_t *img, exports_planner_maxpoolworld_plan_data_t *ret);

// Helper Functions

void maxpoolworld_list_f32_free(maxpoolworld_list_f32_t *ptr);

void maxpoolworld_list_u8_free(maxpoolworld_list_u8_t *ptr);

void exports_planner_maxpoolworld_plan_data_free(exports_planner_maxpoolworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void maxpoolworld_string_set(maxpoolworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void maxpoolworld_string_dup(maxpoolworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void maxpoolworld_string_dup_n(maxpoolworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void maxpoolworld_string_free(maxpoolworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
