package planner:reluworld;

interface plan {

    record data {
        input: list<f32>,
        output: list<f32>,
        reply-to: string,
        kernels: list<u8>,
        current-kernel: u32,
        request: u32
    }
  
    relu: func(img: data) -> data;
    
}

world reluworld {

    export plan;

}