// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#include "reluworld.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `planner:reluworld/plan`

__attribute__((__weak__, __export_name__("cabi_post_planner:reluworld/plan#relu")))
void __wasm_export_exports_planner_reluworld_plan_relu_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 4;
      (void) base;
    }
    free(ptr);
  }
  size_t len0 = *((size_t*) (arg0 + (3*sizeof(void*))));
  if (len0 > 0) {
    uint8_t *ptr1 = *((uint8_t **) (arg0 + (2*sizeof(void*))));
    for (size_t i2 = 0; i2 < len0; i2++) {
      uint8_t *base = ptr1 + i2 * 4;
      (void) base;
    }
    free(ptr1);
  }
  if ((*((size_t*) (arg0 + (5*sizeof(void*))))) > 0) {
    free(*((uint8_t **) (arg0 + (4*sizeof(void*)))));
  }
  size_t len3 = *((size_t*) (arg0 + (7*sizeof(void*))));
  if (len3 > 0) {
    uint8_t *ptr4 = *((uint8_t **) (arg0 + (6*sizeof(void*))));
    for (size_t i5 = 0; i5 < len3; i5++) {
      uint8_t *base = ptr4 + i5 * 1;
      (void) base;
    }
    free(ptr4);
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(8+8*sizeof(void*))];

// Helper Functions

void reluworld_list_f32_free(reluworld_list_f32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    float *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void reluworld_list_u8_free(reluworld_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void exports_planner_reluworld_plan_data_free(exports_planner_reluworld_plan_data_t *ptr) {
  reluworld_list_f32_free(&ptr->input);
  reluworld_list_f32_free(&ptr->output);
  reluworld_string_free(&ptr->reply_to);
  reluworld_list_u8_free(&ptr->kernels);
}

void reluworld_string_set(reluworld_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void reluworld_string_dup(reluworld_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void reluworld_string_dup_n(reluworld_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void reluworld_string_free(reluworld_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("planner:reluworld/plan#relu")))
uint8_t * __wasm_export_exports_planner_reluworld_plan_relu(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2, uint8_t * arg3, size_t arg4, uint8_t * arg5, size_t arg6, int32_t arg7, int32_t arg8) {
  exports_planner_reluworld_plan_data_t arg9 = (exports_planner_reluworld_plan_data_t) {
    (reluworld_list_f32_t) (reluworld_list_f32_t) { (float*)(arg), (arg0) },
    (reluworld_list_f32_t) (reluworld_list_f32_t) { (float*)(arg1), (arg2) },
    (reluworld_string_t) (reluworld_string_t) { (uint8_t*)(arg3), (arg4) },
    (reluworld_list_u8_t) (reluworld_list_u8_t) { (uint8_t*)(arg5), (arg6) },
    (uint32_t) (uint32_t) (arg7),
    (uint32_t) (uint32_t) (arg8),
  };
  exports_planner_reluworld_plan_data_t ret;
  exports_planner_reluworld_plan_relu(&arg9, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = ((ret).input).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).input).ptr;
  *((size_t*)(ptr + (3*sizeof(void*)))) = ((ret).output).len;
  *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) ((ret).output).ptr;
  *((size_t*)(ptr + (5*sizeof(void*)))) = ((ret).reply_to).len;
  *((uint8_t **)(ptr + (4*sizeof(void*)))) = (uint8_t *) ((ret).reply_to).ptr;
  *((size_t*)(ptr + (7*sizeof(void*)))) = ((ret).kernels).len;
  *((uint8_t **)(ptr + (6*sizeof(void*)))) = (uint8_t *) ((ret).kernels).ptr;
  *((int32_t*)(ptr + (8*sizeof(void*)))) = (int32_t) ((ret).current_kernel);
  *((int32_t*)(ptr + (4+8*sizeof(void*)))) = (int32_t) ((ret).request);
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_reluworld(void);
__attribute__((used))
void __component_type_object_force_link_reluworld_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_reluworld();
}
