// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
#ifndef __BINDINGS_RELUWORLD_H
#define __BINDINGS_RELUWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct reluworld_string_t {
  uint8_t*ptr;
  size_t len;
} reluworld_string_t;

typedef struct {
  float *ptr;
  size_t len;
} reluworld_list_f32_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} reluworld_list_u8_t;

typedef struct exports_planner_reluworld_plan_data_t {
  reluworld_list_f32_t   input;
  reluworld_list_f32_t   output;
  reluworld_string_t   reply_to;
  reluworld_list_u8_t   kernels;
  uint32_t   current_kernel;
  uint32_t   request;
} exports_planner_reluworld_plan_data_t;

// Exported Functions from `planner:reluworld/plan`
void exports_planner_reluworld_plan_relu(exports_planner_reluworld_plan_data_t *img, exports_planner_reluworld_plan_data_t *ret);

// Helper Functions

void reluworld_list_f32_free(reluworld_list_f32_t *ptr);

void reluworld_list_u8_free(reluworld_list_u8_t *ptr);

void exports_planner_reluworld_plan_data_free(exports_planner_reluworld_plan_data_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void reluworld_string_set(reluworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void reluworld_string_dup(reluworld_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void reluworld_string_dup_n(reluworld_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void reluworld_string_free(reluworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
